# This file was automatically generated by Natron PyPlug exporter

import NatronEngine
import sys
from util import *


def getPluginID():
    return 'vv.text'


def getLabel():
    return 'VVText'


def getVersion():
    return 1


def getIconPath():
    return 'Text.png'


def getGrouping():
    return 'videovina'


def getPluginDescription():
    return 'Animacion de Textos'


def createInstance(_app, group):
    group.controls = group.createPageParam("controls", "Controls")

    def createParam(name, _type=None, _range=[0, 100]):
        # funcion para crear parametros mas facilmente

        # creacion de parametro
        if _type == 'float':
            param = group.createDoubleParam(name + '_param', name.capitalize())
        elif _type == 'int':
            param = group.createIntParam(name + '_param', name.capitalize())
        elif _type == 'string':
            param = group.createStringParam(name + '_param', name.capitalize())
        elif name == 'separator':
            param = group.createSeparatorParam("sep_" + hash_generator(5), "")
        elif _type == 'button':
            param = group.createButtonParam(name + '_param', name.capitalize())

        # establece el rango de la slide
        allowed = ['float', 'int']
        if _type in allowed:
            param.setMinimum(_range[0], 0)
            param.setMaximum(_range[1], 0)
            param.setDisplayMinimum(_range[0], 0)
            param.setDisplayMaximum(_range[1], 0)
        # ----------------------

        # agrega el parametro a la pestania
        group.controls.addParam(param)
        # ----------------------

    createParam('text', 'string')

    createParam('separator')
    createParam('delay', 'float')

    createParam('separator')
    createParam('scale', 'float', [1, 100])
    createParam('position_y', 'int', [0, 1920])
    createParam('position_x', 'int', [0, 1080])
    createParam('rotate', 'float', [0, 360])
    createParam('opcity', 'float', [0, 1])

    createParam('separator')
    createParam('blur_x', 'float', [0, 100])
    createParam('blur_y', 'float', [0, 100])

    createParam('separator')
    createParam('update', 'button')

    group.onParamChanged.set('vvtext.update_button')

    # cambia el orden de la primera pestania y actualiza
    group.setPagesOrder(['controls', 'Node'])
    group.refreshUserParamsGUI()
    # ----------------------


created_nodes = []


def createNode(name):
    nodes = {
        'blur': 'net.sf.cimg.CImgBlur',
        'text': 'net.fxarena.openfx.Text',
        'transform': 'net.sf.openfx.TransformPlugin',
        'merge': 'net.sf.openfx.MergePlugin',
        'output': 'fr.inria.built-in.Output'
    }

    node_name = _app.createNode(nodes[name], -1, _thisNode).getScriptName()

    node = getattr(_thisNode, node_name)
    created_nodes.append(node)
    return node


def deleteNodes():
    for node in created_nodes:
        node.destroy()
    for node in created_nodes:
        node.destroy()

    del created_nodes[:]


def create_letter(letter, position, index):

    def expression(field, name, index, dimension=0, add=0):
        exp = 'value = thisGroup.' + name + \
            '.curve(frame - ' + str(index) + '*thisGroup.delayParam.get());'
        exp += 'ret = value + ' + str(add)

        field.setExpression(exp, False, dimension)

    # create text
    text = createNode('text')
    text.autoSize.set(True)
    text.text.set(letter)
    # Opacity expression
    for i in range(3):
        expression(text.color, 'opacity_param', index, i)
    # ------------------------

    # Blur
    blur = createNode('blur')
    blur.cropToFormat.set(False)
    blur.connectInput(0, text)
    expression(blur.size, 'blur_x_param', index, 0)
    expression(blur.size, 'blur_y_param', index, 1)
    # ------------------

    letter_width = text.getRegionOfDefinition(1, 1).x2

    transform = createNode('transform')

    # Transform expression
    expression(transform.translate, 'position_x_param', index, 0, position)
    expression(transform.translate, 'position_y_param', index, 1)
    expression(transform.rotate, 'rotate_param', index)
    expression(transform.scale, 'scale_param', index, 0)
    expression(transform.scale, 'scale_param', index, 1)
    # -----------------------

    transform.connectInput(0, blur)

    return [transform, letter_width]


def create_word():
    merge = createNode('merge')
    output = createNode('output')
    output.connectInput(0, merge)

    pos = 0
    word = _thisNode.text_param.get()
    for index, letter in enumerate(word):
        transform, letter_width = create_letter(letter.strip(), pos, index)

        # la entrada numero 2 pertenece a la maskara, asi que la omite
        if index >= 2:
            index += 1

        merge.connectInput(index, transform)
        pos += letter_width


def update_button(thisParam, thisNode, thisGroup, app, userEdited):
    # defina la app y el nodo como variables globales,
    # para poder acceder de otras funcciones
    global _app
    global _thisNode
    _app = app
    _thisNode = thisNode
    # ----------------------

    button_name = thisParam.getScriptName()
    if button_name == 'update_param':
        deleteNodes()
        create_word()
