# This file was automatically generated by Natron PyPlug exporter

import NatronEngine
import sys
from util import *


def getPluginID():
    return 'vv.text'


def getLabel():
    return 'VVText'


def getVersion():
    return 1


def getIconPath():
    return 'Text.png'


def getGrouping():
    return 'videovina'


def getPluginDescription():
    return 'Animacion de Textos'


def createInstance(app, group):

    group.controls = group.createPageParam("controls", "Controls")

    def createParam(name, _type=None, _range=[0, 100]):
        # funcion para crear parametros mas facilmente

        # creacion de parametro
        if _type == 'float':
            param = group.createDoubleParam(name + 'Param', name.capitalize())
        elif _type == 'int':
            param = group.createIntParam(name + 'Param', name.capitalize())
        elif _type == 'string':
            param = group.createStringParam(name + 'Param', name.capitalize())
        elif name == 'separator':
            param = group.createSeparatorParam("sep_" + hash_generator(5), "")
        elif _type == 'button':
            param = group.createButtonParam(name + 'Param', name.capitalize())

        # establece el rango de la slide
        allowed = ['float', 'int']
        if _type in allowed:
            param.setMinimum(_range[0], 0)
            param.setMaximum(_range[1], 0)
            param.setDisplayMinimum(_range[0], 0)
            param.setDisplayMaximum(_range[1], 0)
        # ----------------------

        # agrega el parametro a la pestania
        group.controls.addParam(param)
        # ----------------------

    createParam('text', 'string')

    createParam('separator')
    createParam('delay', 'float')

    createParam('separator')
    createParam('scale', 'float', [1, 100])
    createParam('position_y', 'int', [0, 1920])
    createParam('position_x', 'int', [0, 1080])
    createParam('rotate', 'float', [0, 360])
    createParam('opcity', 'float', [0, 1])

    createParam('separator')
    createParam('blur_x', 'float', [0, 100])
    createParam('blur_y', 'float', [0, 100])

    createParam('separator')
    createParam('update', 'button')

    group.onParamChanged.set('vvtext_update')

    # cambia el orden de la primera pestania y actualiza
    group.setPagesOrder(['controls', 'Node'])
    group.refreshUserParamsGUI()
    # ----------------------
