#!/bin/bash
# chkconfig: 345 99 01
# description: some startup script
. /etc/init.d/functions

pid_file='/opt/cats_farm/os/linux/init/serverPID'
log_file='/opt/cats_farm/log/server.log'
debug=$(cat '/opt/cats_farm/etc/debug')

run() {
	# mata el pid a partir del puerto de catsfarm
	fuser -k 7001/tcp &>/dev/null
	#----------------------------------
	if $debug; then
		rm $log_file &> /dev/null
		echo "Started debugging."
		/opt/rh/devtoolset-7/root/usr/bin/gdb -ex "set logging file $log_file" -ex "set logging redirect on" -ex "set confirm off" -ex "set pagination off" -ex r -ex "set logging on" -ex bt -ex q "./CatsFarm Server" &> /dev/null
	else
		"./CatsFarm Server" &> /dev/null
	fi
}

start() {
 	pid=$(cat $pid_file)

	if ! kill -0 $pid > /dev/null 2>&1; then
		echo "CatsFarm Server has started."
		export DISPLAY=:1 && export QT_QPA_PLATFORM=offscreen &&  cd '/opt/cats_farm/bin/linux' && run &>/dev/null & echo $! > $pid_file
	else
		echo "CatsFarm Server is running now."
	fi
}

stop() {
	cpid=$(cat $pid_file)
	ppid=$(pgrep -P $cpid)

	if kill -0 $cpid > /dev/null 2>&1; then
		kill $ppid
		kill $cpid
		echo "CatsFarm Server has stopped."
	else
		echo "Is not running."
	fi
}

case "$1" in
	start)
		start
	;;
	stop)
		stop
	;;
	status)
		status cserver
	;;
	restart|reload|condrestart)
		stop
		start
	;;
	*)
	echo $"Usage: $0 {start|stop|restart|reload|status}"
	exit 1
esac

exit 0
